services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-lw
    restart: unless-stopped
    networks:
      - pg-lw
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # env_file: .env
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    restart: unless-stopped
    networks:
      - pg-lw
      - traefik_proxy
    # ports:
    #   - 3000:3000
    volumes:
      - ./data:/data/data
    env_file: .env
    environment:
      - DOMAINNAME
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lw-rtr.entrypoints=websecure"
      - "traefik.http.routers.lw-rtr.rule=Host(`lw.$DOMAINNAME`)"
      - "traefik.http.routers.lw-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.lw-rtr.service=lw-svc"
      - "traefik.http.services.lw-svc.loadbalancer.server.port=3000"

networks:
  pg-lw: